export default {
  no_data: "No hay datos disponibles para el día – ¿esperamos los precios?",
  no_data_attributes: "Tu entidad no tiene atributos de datos - consulta el readme",
  no_data_prices: "Tu entidad no tiene precios en el formato correcto - consulta el readme",
  missing_price: "Por favor especifique el sensor 'price' en la configuración",
  label_today_price: "Precio de hoy",
  label_time_nextDay: "Rango de precios",
  label_average_price: "Precio medio",
  label_price: "Precio",
  unit_cent: "Céntimos",
  label_tomorrow_price: "Precio de mañana",
  editor_theme_light: "Claro",
  editor_theme_dark: "Oscuro",
  editor_theme_system: "Sistema",
  editor_price_label: "Sensor de precio",
  editor_price_desc: "Sensor que contiene el precio actual (en el atributo data)",
  editor_average_label: "Opcional: Valor promedio",
  editor_average_desc: "Número (p. ej. 0.225) que indica el precio medio (opcional)",
  editor_theme_label: "Tema",
  editor_theme_desc: "Modo de visualización de la tarjeta.",
  editor_start_today: "Hoy",
  editor_start_tomorrow: "Mañana",
  editor_start_yesterday: "Ayer",
  editor_start_view_label: "Vista inicial",
  editor_start_view_desc: "Vista que se mostrará por defecto",
  editor_view_mode_label: "Modo de vista",
  editor_currency_label: "Moneda",
  editor_currency_desc: "Especifique una moneda personalizada",
  editor_day_switch_label: "Conmutador de día",
  editor_day_switch_desc: "Muestra u oculta el conmutador de día",
};