export default {
  no_data: "No hay datos disponibles para el día – ¿esperamos los precios?",
  no_data_attributes: "Tu entidad no tiene atributos de datos - consulta el readme",
  no_data_prices: "Tu entidad no tiene precios en el formato correcto - consulta el readme",
  missing_price: "Por favor especifique el sensor 'price' en la configuración",
  label_today_price: "Precio de hoy",
  label_time_nextDay: "Rango de precios",
  label_average_price: "Precio medio",
  label_price: "Precio",
  label_day: "Día",
  label_start: "Inicio",
  label_end: "Fin",
  label_duration: "Duración",
  label_name: "Nombre",
  unit_cent: "Céntimos",
  label_tomorrow_price: "Precio de mañana",
  editor_theme_light: "Claro",
  editor_theme_dark: "Oscuro",
  editor_theme_system: "Sistema",
  editor_price_label: "Sensor de precio",
  editor_price_desc: "Sensor que contiene el precio actual (en el atributo data)",
  editor_average_label: "Opcional: Valor promedio",
  editor_average_desc: "Número (p. ej. 0.225) que indica el precio medio (opcional)",
  editor_theme_label: "Tema",
  editor_theme_desc: "Modo de visualización de la tarjeta.",
  editor_start_today: "Hoy",
  editor_start_tomorrow: "Mañana",
  editor_start_yesterday: "Ayer",
  editor_start_view_label: "Vista inicial",
  editor_start_view_desc: "Vista que se mostrará por defecto",
  editor_view_mode_label: "Modo de vista",
  editor_slider_label: "Control deslizante",
  editor_slider_desc: "Mostrar un control deslizante para navegar por las franjas horarias",
  editor_currency_label: "Moneda",
  editor_currency_desc: "Especifique una moneda personalizada",
  editor_color_scheme_label: "Esquema de colores",
  editor_color_scheme_desc: "Elija cómo se colorean los precios",
  editor_gradient_fill_label: "Relleno degradado",
  editor_gradient_fill_desc: "Mostrar un relleno degradado de color bajo la línea del gráfico",
  editor_day_switch_label: "Conmutador de día",
  editor_day_switch_desc: "Muestra u oculta el conmutador de día",
  editor_cheap_times_label: "Tiempos económicos",
  editor_cheap_times_desc: "Visualización de intervalos de tiempo económicos",
  editor_display_settings: "Configuración de visualización",
  editor_navigation_settings: "Configuración de período",
  editor_price_optimization: "Optimización de precios",
  editor_appearance_settings: "Apariencia",
};