export default {
  no_data: "Geen gegevens voor vandaag – wachten we nog op de prijzen?",
  no_data_attributes: "Je entiteit heeft geen data-attributen – zie readme",
  no_data_prices: "Je entiteit heeft geen prijzen in het juiste formaat – zie readme",
  missing_price: "Geef alstublieft de 'price'-sensor op in de configuratie",
  label_today_price: "Prijs van vandaag",
  label_time_nextDay: "Tijdsperiode",
  unit_cent: "Cent",
  label_tomorrow_price: "Prijs van morgen",
  label_average_price: "Gemiddelde prijs",
  label_price: "Prijs",
  label_day: "Dag",
  label_start: "Start",
  label_end: "Einde",
  label_duration: "Duur",
  label_name: "Naam",
  editor_theme_light: "Licht",
  editor_theme_dark: "Donker",
  editor_theme_system: "Systeem",
  editor_price_label: "Prijs-sensor",
  editor_price_desc: "Sensor die de actuele prijs bevat (in data-attributen)",
  editor_average_label: "Optioneel: Gemiddelde waarde",
  editor_average_desc: "Getal (bijv. 0.225) dat de gemiddelde prijs aangeeft (optioneel)",
  editor_theme_label: "Thema",
  editor_theme_desc: "Weergavemodus van de kaart.",
  editor_start_today: "Vandaag",
  editor_start_tomorrow: "Morgen",
  editor_start_yesterday: "Gisteren",
  editor_start_view_label: "Startweergave",
  editor_start_view_desc: "Weergave die standaard wordt getoond",
  editor_view_mode_label: "Weergavemodus",
  editor_slider_label: "Schuifregelaar",
  editor_slider_desc: "Toon een schuifregelaar om door tijdsloten te navigeren",
  editor_currency_label: "Valuta",
    editor_graph_hours_label: "Grafiekperiode (uren)",
    editor_graph_hours_desc: "Hoeveel komende uren moeten worden getoond in de grafiekweergave",
  editor_graph_start_from_label: "Grafiek vanaf nu",
  editor_graph_start_from_desc: "Wanneer ingeschakeld begint de grafiek vanaf nu in plaats van middernacht",
  editor_graph_start_now: "Nu",
  editor_graph_start_midnight: "Middernacht",
  editor_currency_desc: "Eigen valuta opgeven",
  editor_color_scheme_label: "Kleurenschema",
  editor_color_scheme_desc: "Kies hoe prijzen worden gekleurd",
  editor_gradient_fill_label: "Verloop vulling",
  editor_gradient_fill_desc: "Toon een gekleurde verloop vulling onder de grafieklijn",
  editor_day_switch_label: "Dagwisselaar",
  editor_day_switch_desc: "Toont of verbergt de dagwisselaar",
  editor_cheap_times_label: "Goedkope tijden",
  editor_cheap_times_desc: "Weergave van goedkope tijdsintervallen",
  editor_display_settings: "Weergave-instellingen",
  editor_navigation_settings: "Periode-instellingen",
  editor_price_optimization: "Prijsoptimalisatie",
  editor_appearance_settings: "Uiterlijk",
  editor_price_calculation: "Prijsberekening",
  editor_enabled_label: "Prijsberekening inschakelen",
  editor_enabled_desc: "Pas een formule toe bovenop de ruwe marktprijssensor",
  editor_display_label: "Prijs weergeven als",
  editor_display_desc: "Ruwe marktprijs, all-in afnameprijs of terugleverprijs weergeven",
  editor_price_calc_market: "Marktprijs (ruw)",
  editor_price_calc_grid: "Afname / Consumptie",
  editor_price_calc_feed_in: "Teruglevering",
  editor_grid_addition_label: "Afname: Vaste opslag (€/kWh)",
  editor_grid_addition_desc: "Vast bedrag in €/kWh bovenop marktprijs voor afname (bijv. netwerk + energiebelasting + marge)",
  editor_grid_tax_label: "Afname: BTW (%)",
  editor_grid_tax_desc: "Percentage na opslag, bijv. 21 voor 21% BTW",
  editor_feed_in_addition_label: "Teruglevering: Vaste opslag (€/kWh)",
  editor_feed_in_addition_desc: "Vast bedrag in €/kWh voor teruglevering (negatief = korting, bijv. -0.02)",
  editor_feed_in_tax_label: "Teruglevering: BTW (%)",
  editor_feed_in_tax_desc: "Percentage na opslag voor teruglevering",
  editor_grid_charges_label: "Afname: Kosten (€/kWh)",
  editor_grid_charges_desc: "Kosten per kWh voor netbeheerkosten en energiebelasting",
  editor_feed_in_charges_label: "Teruglevering: Compensatie (€/kWh)",
  editor_feed_in_charges_desc: "Compensatie per kWh voor teruglevering",
  editor_fixed_per_kwh_label: "Vaste kosten (€/kWh)",
  editor_fixed_per_kwh_desc: "Vaste toeslag (per kWh) voor berekening",
  editor_energy_tax_per_kwh_label: "Energiebelasting (€/kWh)",
  editor_energy_tax_per_kwh_desc: "Energiebelasting per kWh",
};
