export default {
  no_data: "Inga data för dagen – vi väntar fortfarande på priserna?",
  no_data_attributes: "Din entitet har inga data-attribut – se readme",
  no_data_prices: "Din entitet har inga priser i rätt format – se readme",
  missing_price: "Vänligen ange 'price'-sensorn i konfigurationen",
  label_today_price: "Dagens pris",
  label_time_nextDay: "Tidsintervall",
  unit_cent: "Cent",
  label_tomorrow_price: "Morgondagens pris",
  label_average_price: "Genomsnittspris",
  label_price: "Pris",
  label_day: "Dag",
  label_start: "Start",
  label_end: "Slut",
  label_duration: "Varaktighet",
  label_name: "Namn",
  editor_theme_light: "Ljus",
  editor_theme_dark: "Mörk",
  editor_theme_system: "System",
  editor_price_label: "Pris-sensor",
  editor_price_desc: "Sensor som innehåller det aktuella priset (i attributet data)",
  editor_average_label: "Valfritt: Genomsnittsvärde",
  editor_average_desc: "Tal (t.ex. 0.225) som anger genomsnittspriset (valfritt)",
  editor_theme_label: "Tema",
  editor_theme_desc: "Visningsläge för kortet.",
  editor_start_today: "Idag",
  editor_start_tomorrow: "Imorgon",
  editor_start_yesterday: "Igår",
  editor_start_view_label: "Startvy",
  editor_start_view_desc: "Vy som visas som standard",
  editor_view_mode_label: "Visningsläge",
  editor_currency_label: "Valuta",
  editor_currency_desc: "Ange egen valuta",
  editor_color_scheme_label: "Färgschema",
  editor_color_scheme_desc: "Välj hur priser färgläggs",
  editor_day_switch_label: "Dagsväxlare",
  editor_day_switch_desc: "Visar eller döljer dagsväxlaren",
  editor_slider_label: "Skjutreglage",
  editor_slider_desc: "Visa ett skjutreglage för att navigera genom tidsperioder",
  editor_cheap_times_label: "Billiga tider",
  editor_cheap_times_desc: "Visning av billiga tidsintervaller",
  editor_display_settings: "Visningsinställningar",
  editor_navigation_settings: "Periodinställningar",
  editor_price_optimization: "Prisoptimering",
  editor_appearance_settings: "Utseende",
};
